syntax = "proto3";

option csharp_namespace = "Discount.Grpc";

package discount;

// The discount service definition.
service DiscountProtoService {
  
  //Discount CRUD opérations
  rpc GetDiscount (GetDiscountRequest) returns (CouponModel);
  rpc CreateDiscount (CreateDiscountRequest) returns (CouponModel);
  rpc UpdateDiscount (UpdateDiscountRequest) returns (CouponModel);
  rpc DeleteDiscount (DeleteDiscountRequest) returns (DeleteDiscountResponse);
  
}

message GetDiscountRequest {
  string productName = 1;
}

enum DiscountType {
  NONE = 0;
  PERCENTAGE = 1;
  FIXED_AMOUNT = 2;
  COMBINED = 3;
}

message CouponModel {
  int32 id = 1;
  string productName = 2;
  string description = 3;
  DiscountType discountType = 4;
  double percentage = 5;
  double amount = 6;
  string couponCode = 7;
  bool isActive = 8;
  bool isStackable = 9;
  double maxStackablePercentage = 10;
}

message CreateDiscountRequest {
  CouponModel coupon = 1;
}

message UpdateDiscountRequest {
  CouponModel coupon = 1;
}

message DeleteDiscountRequest {
  CouponModel coupon = 1;
}

message DeleteDiscountResponse {
  bool success = 1;
}
